name = "WebSockets"
uuid = "104b5d7c-a370-577a-8038-80a2059c5097"
authors = ["Leah Hanson", "Stefan Karpinski", "Zach Allaun", "Daniel Espeset", "Jacob Quinn", "Sam O'Connor", "contributors: https://github.com/JuliaWeb/WebSockets.jl/graphs/contributors", "contributors: https://github.com/JuliaWeb/HTTP.jl/graphs/contributors"]
version = "1.3.1+"

[deps]
Base64 = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
MbedTLS = "739be429-bea8-5141-9913-cc70e7f3736d"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
